export const TYPE_NAMES = {
  typeless: "无属性",
  normal: "一般",
  fire: "火",
  water: "水",
  electric: "电",
  grass: "草",
  ice: "冰",
  fighting: "格斗",
  poison: "毒",
  ground: "地面",
  flying: "飞行",
  psychic: "超能力",
  bug: "虫",
  rock: "岩石",
  ghost: "幽灵",
  dragon: "龙",
  dark: "恶",
  steel: "钢",
  fairy: "妖精",
};

export const STATUS_NAMES = {
  burn: "灼伤",
  poison: "中毒",
  paralysis: "麻痹",
  sleep: "睡眠",
  freeze: "冰冻",
};

export const STAT_NAMES = {
  attack: "攻击",
  defense: "防御",
  specialAttack: "特攻",
  specialDefense: "特防",
  speed: "速度",
  accuracy: "命中",
  evasion: "闪避",
};

export const MOVES = {
  thunderbolt: {
    id: "thunderbolt",
    name: "十万伏特",
    type: "electric",
    category: "special",
    power: 90,
    accuracy: 100,
    maxPp: 15,
    description: "有 10% 几率使目标麻痹。",
    effects: [{ kind: "status", status: "paralysis", chance: 0.1, target: "foe" }],
  },
  quickAttack: {
    id: "quickAttack",
    name: "电光一闪",
    type: "normal",
    category: "physical",
    power: 40,
    accuracy: 100,
    maxPp: 30,
    priority: 1,
    description: "优先度 +1，通常会先出手。",
  },
  thunderWave: {
    id: "thunderWave",
    name: "电磁波",
    type: "electric",
    category: "status",
    power: 0,
    accuracy: 90,
    maxPp: 20,
    checksTypeImmunity: true,
    description: "使目标麻痹。地面属性免疫。",
    effects: [{ kind: "status", status: "paralysis", chance: 1, target: "foe" }],
  },
  ironTail: {
    id: "ironTail",
    name: "铁尾",
    type: "steel",
    category: "physical",
    power: 100,
    accuracy: 75,
    maxPp: 15,
    description: "有 30% 几率降低目标防御。",
    effects: [{ kind: "stat", stat: "defense", stages: -1, chance: 0.3, target: "foe" }],
  },
  dragonClaw: {
    id: "dragonClaw",
    name: "龙爪",
    type: "dragon",
    category: "physical",
    power: 80,
    accuracy: 100,
    maxPp: 15,
    description: "用锋利的巨爪劈开目标。",
  },
  waterGun: {
    id: "waterGun",
    name: "水枪",
    type: "water",
    category: "special",
    power: 40,
    accuracy: 100,
    maxPp: 25,
    description: "向目标喷射水流。",
  },
  tackle: {
    id: "tackle",
    name: "撞击",
    type: "normal",
    category: "physical",
    power: 40,
    accuracy: 100,
    maxPp: 35,
    description: "用整个身体撞向目标。",
  },
  tailWhip: {
    id: "tailWhip",
    name: "摇尾巴",
    type: "normal",
    category: "status",
    power: 0,
    accuracy: 100,
    maxPp: 30,
    description: "令目标防御降低 1 级。",
    effects: [{ kind: "stat", stat: "defense", stages: -1, chance: 1, target: "foe" }],
  },
  iceBeam: {
    id: "iceBeam",
    name: "冰冻光束",
    type: "ice",
    category: "special",
    power: 90,
    accuracy: 100,
    maxPp: 10,
    description: "有 10% 几率使目标冰冻。",
    effects: [{ kind: "status", status: "freeze", chance: 0.1, target: "foe" }],
  },
  razorLeaf: {
    id: "razorLeaf",
    name: "飞叶快刀",
    type: "grass",
    category: "physical",
    power: 55,
    accuracy: 95,
    maxPp: 25,
    critStage: 1,
    description: "容易击中要害。",
  },
  sleepPowder: {
    id: "sleepPowder",
    name: "催眠粉",
    type: "grass",
    category: "status",
    power: 0,
    accuracy: 75,
    maxPp: 15,
    powder: true,
    description: "使目标陷入 1–3 回合的睡眠。草属性免疫粉末。",
    effects: [{ kind: "status", status: "sleep", chance: 1, target: "foe" }],
  },
  growth: {
    id: "growth",
    name: "生长",
    type: "normal",
    category: "status",
    power: 0,
    accuracy: null,
    maxPp: 20,
    description: "令自己的攻击与特攻各提高 1 级。",
    effects: [
      { kind: "stat", stat: "attack", stages: 1, chance: 1, target: "self" },
      { kind: "stat", stat: "specialAttack", stages: 1, chance: 1, target: "self" },
    ],
  },
  ember: {
    id: "ember",
    name: "火花",
    type: "fire",
    category: "special",
    power: 40,
    accuracy: 100,
    maxPp: 25,
    description: "有 10% 几率使目标灼伤。",
    effects: [{ kind: "status", status: "burn", chance: 0.1, target: "foe" }],
  },
  scratch: {
    id: "scratch",
    name: "抓",
    type: "normal",
    category: "physical",
    power: 40,
    accuracy: 100,
    maxPp: 35,
    description: "用锋利的爪子攻击。",
  },
  growl: {
    id: "growl",
    name: "叫声",
    type: "normal",
    category: "status",
    power: 0,
    accuracy: 100,
    maxPp: 40,
    description: "令目标攻击降低 1 级。",
    effects: [{ kind: "stat", stat: "attack", stages: -1, chance: 1, target: "foe" }],
  },
  smokescreen: {
    id: "smokescreen",
    name: "烟幕",
    type: "normal",
    category: "status",
    power: 0,
    accuracy: 100,
    maxPp: 20,
    description: "令目标命中降低 1 级。",
    effects: [{ kind: "stat", stat: "accuracy", stages: -1, chance: 1, target: "foe" }],
  },
  rockThrow: {
    id: "rockThrow",
    name: "落石",
    type: "rock",
    category: "physical",
    power: 50,
    accuracy: 90,
    maxPp: 15,
    description: "投掷岩石攻击目标。",
  },
  defenseCurl: {
    id: "defenseCurl",
    name: "变圆",
    type: "normal",
    category: "status",
    power: 0,
    accuracy: null,
    maxPp: 40,
    description: "令自己的防御提高 1 级。",
    effects: [{ kind: "stat", stat: "defense", stages: 1, chance: 1, target: "self" }],
  },
  bulldoze: {
    id: "bulldoze",
    name: "重踏",
    type: "ground",
    category: "physical",
    power: 60,
    accuracy: 100,
    maxPp: 20,
    description: "命中后令目标速度降低 1 级。",
    effects: [{ kind: "stat", stat: "speed", stages: -1, chance: 1, target: "foe" }],
  },
  shadowBall: {
    id: "shadowBall",
    name: "暗影球",
    type: "ghost",
    category: "special",
    power: 80,
    accuracy: 100,
    maxPp: 15,
    description: "有 20% 几率降低目标特防。",
    effects: [{ kind: "stat", stat: "specialDefense", stages: -1, chance: 0.2, target: "foe" }],
  },
  lick: {
    id: "lick",
    name: "舌舔",
    type: "ghost",
    category: "physical",
    power: 30,
    accuracy: 100,
    maxPp: 30,
    description: "有 30% 几率使目标麻痹。",
    effects: [{ kind: "status", status: "paralysis", chance: 0.3, target: "foe" }],
  },
  hypnosis: {
    id: "hypnosis",
    name: "催眠术",
    type: "psychic",
    category: "status",
    power: 0,
    accuracy: 60,
    maxPp: 20,
    description: "使目标陷入 1–3 回合的睡眠。",
    effects: [{ kind: "status", status: "sleep", chance: 1, target: "foe" }],
  },
  confuseRay: {
    id: "confuseRay",
    name: "奇异之光",
    type: "ghost",
    category: "status",
    power: 0,
    accuracy: 100,
    maxPp: 10,
    description: "使目标混乱 2–5 回合。",
    effects: [{ kind: "confusion", chance: 1, target: "foe" }],
  },
  struggle: {
    id: "struggle",
    name: "挣扎",
    type: "typeless",
    category: "physical",
    power: 50,
    accuracy: null,
    maxPp: 1,
    recoil: 0.25,
    description: "没有可用招式时使出，并承受最大 HP 1/4 的反作用力。",
  },
};

export const SPECIES = {
  pikachu: {
    id: "pikachu",
    dex: 25,
    name: "皮卡丘",
    types: ["electric"],
    baseStats: { hp: 35, attack: 55, defense: 40, specialAttack: 50, specialDefense: 50, speed: 90 },
    moveIds: ["thunderbolt", "quickAttack", "thunderWave", "ironTail"],
    sprite: "assets/sprites/pikachu-back.gif",
    videoReference: "assets/video-references/pikachu-back.png",
    accent: "#f4c84a",
  },
  squirtle: {
    id: "squirtle",
    dex: 7,
    name: "杰尼龟",
    types: ["water"],
    baseStats: { hp: 44, attack: 48, defense: 65, specialAttack: 50, specialDefense: 64, speed: 43 },
    moveIds: ["waterGun", "tackle", "tailWhip", "iceBeam"],
    sprite: "assets/sprites/squirtle-back.gif",
    videoReference: "assets/video-references/squirtle-back.png",
    accent: "#64b4dc",
  },
  bulbasaur: {
    id: "bulbasaur",
    dex: 1,
    name: "妙蛙种子",
    types: ["grass", "poison"],
    baseStats: { hp: 45, attack: 49, defense: 49, specialAttack: 65, specialDefense: 65, speed: 45 },
    moveIds: ["razorLeaf", "tackle", "sleepPowder", "growth"],
    sprite: "assets/sprites/bulbasaur-back.gif",
    videoReference: "assets/video-references/bulbasaur-back.png",
    accent: "#72c879",
  },
  charmander: {
    id: "charmander",
    dex: 4,
    name: "小火龙",
    types: ["fire"],
    baseStats: { hp: 39, attack: 52, defense: 43, specialAttack: 60, specialDefense: 50, speed: 65 },
    moveIds: ["ember", "scratch", "growl", "smokescreen"],
    sprite: "assets/sprites/charmander-front.gif",
    videoReference: "assets/video-references/charmander-front.png",
    accent: "#ef7744",
  },
  geodude: {
    id: "geodude",
    dex: 74,
    name: "小拳石",
    types: ["rock", "ground"],
    baseStats: { hp: 40, attack: 80, defense: 100, specialAttack: 30, specialDefense: 30, speed: 20 },
    moveIds: ["rockThrow", "tackle", "defenseCurl", "bulldoze"],
    sprite: "assets/sprites/geodude-front.gif",
    videoReference: "assets/video-references/geodude-front.png",
    accent: "#a99981",
  },
  gastly: {
    id: "gastly",
    dex: 92,
    name: "鬼斯",
    types: ["ghost", "poison"],
    baseStats: { hp: 30, attack: 35, defense: 30, specialAttack: 100, specialDefense: 35, speed: 80 },
    moveIds: ["shadowBall", "lick", "hypnosis", "confuseRay"],
    sprite: "assets/sprites/gastly-front.gif",
    videoReference: "assets/video-references/gastly-front.png",
    accent: "#8d69b4",
  },
  dragonite: {
    id: "dragonite",
    dex: 149,
    name: "快龙",
    types: ["dragon", "flying"],
    baseStats: { hp: 91, attack: 134, defense: 95, specialAttack: 100, specialDefense: 100, speed: 80 },
    moveIds: ["dragonClaw", "ironTail", "thunderWave", "iceBeam"],
    sprite: "assets/sprites/dragonite-front.gif",
    videoReference: "assets/video-references/dragonite-front.png",
    accent: "#e8a34f",
  },
  gengar: {
    id: "gengar",
    dex: 94,
    name: "耿鬼",
    types: ["ghost", "poison"],
    baseStats: { hp: 60, attack: 65, defense: 60, specialAttack: 130, specialDefense: 75, speed: 110 },
    moveIds: ["shadowBall", "lick", "hypnosis", "confuseRay"],
    sprite: "assets/sprites/gengar-front.gif",
    videoReference: "assets/video-references/gengar-front.png",
    accent: "#8063a5",
  },
};

export const ITEMS = {
  potion: {
    id: "potion",
    name: "伤药",
    description: "回复一只宝可梦 20 点 HP。",
    heal: 20,
    initialCount: 2,
    symbol: "+",
  },
  fullHeal: {
    id: "fullHeal",
    name: "万灵药",
    description: "治愈异常状态与混乱。",
    cure: true,
    initialCount: 1,
    symbol: "✦",
  },
};
